pwd
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
python3 ./server/bd.py
